# Welcome to Jekyll!
#

# Site settings
title: Anna Wang
description: Storyteller // Maker // Coder
owner: Anna Wang # or company name
first_published: 2018 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://annawang7.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Social Media settings
github-url: annawang7
linkedin: annawang7
email: annawang1@college.harvard.edu
