<<<<<<< HEAD
# Default, Defaults
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Anna Wang
email: annawang1@college.harvard.edu
description: Thinker | Maker | Hello World-er

# Where can people find your site?
url: "http://localhost:4000"
# When developing, set this ^ equal to whatever localhost you're using

# Social Media links
# Use these to link users to your organization's social media sites
twitter:
facebook:
google:

author: Anna Wang
authorBio:
=======
# Welcome to Jekyll!
#

# Site settings
title: Anna Wang
description: |
  Personal Website
owner: Anna Wang # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: annawang1@college.harvard.edu
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://annawang7.github.io" # the base hostname & protocol for your site
social:
  github: https://github.com/annawang7
  linkedin-square: https://linkedin.com/in/annawang7
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
#sass:
#  style: compressed
>>>>>>> parent of dc2bf59... Change theme
